(function(){"use strict";
const D=window.APPARATUS_DATA;const C=window.REVIEW_CONFIG||{};if(!D)return;
const reviewer=C.reviewer||"";const revision=C.manifestRevision||"unmanifested";const key=`sundara-review:${reviewer}:${revision}:${D.sarga}`;
let decisions={};try{decisions=JSON.parse(localStorage.getItem(key)||"{}");}catch(_){decisions={};}
const root=document.getElementById("app");const status=document.getElementById("sync-status");
function esc(value){return String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function setState(name,detail){status.className=`status-pill status-${name}`;status.textContent={local:"local",syncing:"syncing…",synced:"synced",offline:"offline/local",conflict:"conflict",submitted:"submitted",error:"sync error"}[name]||name;status.setAttribute("role","status");document.getElementById("sync-detail").textContent=detail||"";}
const sync=new ReviewSync({base:C.apiBase||"",revision,sarga:D.sarga,onState:setState});
function votable(){return D.verses.flatMap(v=>v.notes).filter(n=>n.votable);}
function validRecord(n,rec){if(!rec||!["accept","edit","reject"].includes(rec.action))return false;if(rec.action==="edit"&&!String(rec.edited_note||"").trim())return false;if(rec.action==="reject"&&!String(rec.reject_reason||"").trim())return false;return true;}
function persist(){localStorage.setItem(key,JSON.stringify(decisions));setState(navigator.onLine?"local":"offline","Local draft saved.");progress();window.dispatchEvent(new CustomEvent("review-draft-change",{detail:{sarga:D.sarga}}));}
function progress(){const all=votable();const done=all.filter(n=>validRecord(n,decisions[n.id])).length;document.getElementById("progress").textContent=`${done}/${all.length} complete`;}
function verdicts(n){return Object.keys(n.gate_verdicts||{}).sort().map(r=>{const v=n.gate_verdicts[r];const mine=r===reviewer;return `<div class="${mine?"mine":"colleague"}"><b>${esc(r)}</b>: ${esc(v.action)}${v.gated_date?` · ${esc(v.gated_date)}`:""}${v.edited_note?`<div>${esc(v.edited_note)}</div>`:""}${v.reject_reason?`<div>${esc(v.reject_reason)}</div>`:""}</div>`;}).join("");}
function noteHtml(n){const rec=decisions[n.id]||{};const controls=n.votable?`<fieldset class="controls"><legend class="hidden">Решение для ${esc(n.id)}</legend>${["accept","edit","reject"].map(a=>`<label><input type="radio" name="a_${esc(n.id)}" value="${a}" ${rec.action===a?"checked":""}>${{accept:"✅ принять",edit:"✏️ править",reject:"❌ отклонить"}[a]}</label>`).join("")}</fieldset><textarea data-edit="${esc(n.id)}" class="${rec.action==="edit"?"":"hidden"}" aria-label="Исправленный текст">${esc(rec.edited_note||n.note_ru||"")}</textarea><input data-reject="${esc(n.id)}" class="reject-reason ${rec.action==="reject"?"":"hidden"}" aria-label="Причина отклонения" value="${esc(rec.reject_reason||"")}">`:"";
return `<article class="note l-${esc(n.layer)} ${rec.action?`d-${esc(rec.action)}`:""}" data-note="${esc(n.id)}"><div><span class="badge b-${esc(n.layer)}">${esc(n.layer_label)}</span><span class="badge b-status">${esc(n.status)}</span></div><p>${n.lemma_iast?`<span class="lemma">${esc(n.lemma_iast)}</span> — `:""}${esc(n.note_ru||"")}</p>${n.source?`<div class="meta">Источник: ${esc(n.source)}</div>`:""}${verdicts(n)}${controls}</article>`;}
function render(){root.textContent="";const legend=document.createElement("section");legend.className="legend";legend.textContent=`Песнь ${D.sarga}. Ярус 1 доступен только для чтения; голосование относится к остальным слоям.`;root.appendChild(legend);D.verses.forEach(v=>{const card=document.createElement("section");card.className="vcard";card.innerHTML=`<div class="vhead"><b>${esc(v.verse_id)}</b></div><div class="verse"><div class="sa">${esc(v.sanskrit_iast)||"—"}</div><div class="ru">${esc(v.leonov_ru)||"—"}</div></div>${v.notes.map(noteHtml).join("")}`;root.appendChild(card);});bind();progress();}
function bind(){root.querySelectorAll("input[type=radio]").forEach(input=>input.addEventListener("change",()=>{const article=input.closest("[data-note]");const id=article.dataset.note;const note=votable().find(n=>n.id===id);const rec=decisions[id]||{verse_id:note.verse_id,layer:note.layer,lemma_iast:note.lemma_iast||""};rec.action=input.value;rec.ts=new Date().toISOString();const edit=article.querySelector("[data-edit]");const reject=article.querySelector("[data-reject]");edit.classList.toggle("hidden",rec.action!=="edit");reject.classList.toggle("hidden",rec.action!=="reject");rec.edited_note=edit.value;rec.reject_reason=reject.value;decisions[id]=rec;article.className=article.className.replace(/\bd-(accept|edit|reject)\b/g,"").trim()+` d-${rec.action}`;persist();}));root.querySelectorAll("[data-edit],[data-reject]").forEach(input=>input.addEventListener("input",()=>{const id=input.dataset.edit||input.dataset.reject;const rec=decisions[id]||{};if(input.dataset.edit)rec.edited_note=input.value;else rec.reject_reason=input.value;decisions[id]=rec;persist();}));}
function aggregate(){const payload={schema_version:1,reviewer,manifest_hash:C.manifestHash||"",source_hash:C.sourceHash||"",client_timestamp:new Date().toISOString(),sargas:[{sarga:D.sarga,source_hash:D._meta.source_hash||"",decisions}]};return payload;}
function download(){const body=JSON.stringify(aggregate(),null,2);const url=URL.createObjectURL(new Blob([body],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`decisions_sarga_${D.sarga}_kostina.json`;a.click();URL.revokeObjectURL(url);}
document.getElementById("download").addEventListener("click",download);document.getElementById("remote-save").addEventListener("click",()=>sync.save(decisions).catch(()=>{}));document.getElementById("submit").addEventListener("click",async()=>{const missing=votable().filter(n=>!validRecord(n,decisions[n.id]));if(missing.length){setState("error",`${missing.length} decisions are incomplete; final submission was not sent.`);return;}if(!confirm("Final submission is explicit and immutable. Continue?"))return;await sync.submit(aggregate()).catch(()=>{});});
window.addEventListener("online",()=>setState("local","Online; remote sync is available."));window.addEventListener("offline",()=>setState("offline","Local draft remains safe."));window.reviewPlatform={aggregate,validRecord,key};setState(navigator.onLine?"local":"offline","Local draft ready.");render();
})();
