(function(){"use strict";
const M=window.REVIEW_MANIFEST;if(!M)return;const grid=document.getElementById("sarga-grid");const status=document.getElementById("portal-status");
function read(entry){try{return JSON.parse(localStorage.getItem(`sundara-review:${M.reviewer}:${entry.source_hash}:${entry.sarga}`)||"{}");}catch(_){return{};}}
function complete(rec){return rec&&["accept","edit","reject"].includes(rec.action)&&(rec.action!=="edit"||String(rec.edited_note||"").trim())&&(rec.action!=="reject"||String(rec.reject_reason||"").trim());}
function counts(entry){const decisions=read(entry);return {done:Object.values(decisions).filter(complete).length,total:entry.votable_count,decisions};}
function render(){grid.textContent="";let done=0,total=0;M.sargas.forEach(entry=>{const c=counts(entry);done+=c.done;total+=c.total;const card=document.createElement("article");card.className="portal-card";card.innerHTML=`<h2>Песнь ${entry.sarga}</h2><p>${c.done}/${c.total} решений</p><div class="progress-track" aria-label="Прогресс песни ${entry.sarga}"><div class="progress-fill" style="width:${c.total?100*c.done/c.total:100}%"></div></div><p><a class="action" href="${entry.url}">${c.done?"Продолжить":"Открыть"}</a></p>`;grid.appendChild(card);});status.textContent=`Всего: ${done}/${total} решений`;status.dataset.complete=String(done===total);}
function unsignedPayload(){return {schema_version:1,reviewer:M.reviewer,manifest_hash:M.manifest_hash,source_hash:M.source_hash,client_timestamp:new Date().toISOString(),sargas:M.sargas.map(entry=>({sarga:entry.sarga,source_hash:entry.source_hash,decisions:counts(entry).decisions}))};}
async function signedPayload(){const payload=unsignedPayload();const canonical=JSON.stringify(payload);const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical));payload.content_hash=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");return payload;}
async function download(){const payload=await signedPayload();const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="kostina_sundara_all68_submission.json";a.click();URL.revokeObjectURL(url);}
document.getElementById("aggregate-download").addEventListener("click",download);document.getElementById("final-submit").addEventListener("click",async()=>{render();if(status.dataset.complete!=="true"){status.textContent+=" — окончательная отправка заблокирована до полного бюллетеня";return;}status.textContent="Hosted submission is not configured here; download the aggregate JSON without losing work.";});window.addEventListener("review-draft-change",render);window.addEventListener("storage",render);window.reviewPortal={unsignedPayload,signedPayload,counts};if("serviceWorker" in navigator)navigator.serviceWorker.register("review-sw.js").catch(()=>{});render();
})();
