import test from "node:test";import assert from "node:assert/strict";import worker from "../src/index.js";import {authCallback,signed} from "../src/auth.js";import {submit} from "../src/submit.js";
class DB{constructor(){this.drafts=new Map();this.submissions=new Map();}prepare(sql){const db=this;return {args:[],bind(...args){this.args=args;return this;},async first(){if(sql.includes("FROM drafts")){await new Promise(r=>setTimeout(r,0));const k=this.args.slice(0,3).join("|");return db.drafts.get(k)||null;}if(sql.includes("FROM submissions"))return db.submissions.get(this.args[0])||null;return null;},async run(){if(sql.includes("INTO drafts")){const [reviewer,rev,sarga,json,hash,updated]=this.args;const k=[reviewer,rev,sarga].join("|");const row=db.drafts.get(k);if(row)return {success:true,meta:{changes:0}};db.drafts.set(k,{version:1,decisions_json:json,content_hash:hash,updated_at:updated});return {success:true,meta:{changes:1}};}if(sql.startsWith("UPDATE drafts")){const [json,hash,updated,reviewer,rev,sarga,expected]=this.args;const k=[reviewer,rev,sarga].join("|");const row=db.drafts.get(k);if(row&&row.version===expected){db.drafts.set(k,{version:row.version+1,decisions_json:json,content_hash:hash,updated_at:updated});return {success:true,meta:{changes:1}};}return {success:true,meta:{changes:0}};}if(sql.includes("INTO submissions")){const [hash,reviewer,pr_url,created_at]=this.args;db.submissions.set(hash,{reviewer,pr_url,created_at});}return {success:true,meta:{changes:1}};}};}}
const origin="https://gasyoun.github.io";const secret="test-secret-long-enough";
async function env(extra={}){return {DB:new DB(),PAGES_ORIGIN:origin,SESSION_SECRET:secret,GITHUB_OAUTH_CLIENT_ID:"id",GITHUB_OAUTH_CLIENT_SECRET:"secret",ALLOWED_GITHUB_LOGIN:"kostina-test",...extra};}
async function authHeaders(){const csrf="csrf-value";const token=await signed(JSON.stringify({reviewer:"Костина",login:"kostina-test",csrf,exp:Date.now()+60000}),secret);return {origin,cookie:`review_session=${encodeURIComponent(token)}; review_csrf=${csrf}`,"x-review-csrf":csrf,"content-type":"application/json"};}
function canonical(value){if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical(value[k])}`).join(",")}}`;return JSON.stringify(value);}
async function payload(){const doc={schema_version:1,reviewer:"Костина",manifest_hash:"a".repeat(64),source_hash:"b".repeat(64),client_timestamp:"2026-08-14T00:00:00.000Z",sargas:Array.from({length:68},(_,i)=>({sarga:i+1,source_hash:"c".repeat(64),decisions:{}}))};const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(doc)));doc.content_hash=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");return doc;}
test("health is public, free-plan, and secret-free",async()=>{const response=await worker.fetch(new Request("https://api.test/health"),await env());const body=await response.json();assert.equal(response.status,200);assert.equal(body.plan,"free");assert.equal(JSON.stringify(body).includes("secret"),false);});
test("invalid origin and missing session fail closed",async()=>{assert.equal((await worker.fetch(new Request("https://api.test/drafts/"+"a".repeat(64)+"/1",{headers:{origin:"https://evil.test"}}),await env())).status,403);assert.equal((await worker.fetch(new Request("https://api.test/drafts/"+"a".repeat(64)+"/1",{headers:{origin}}),await env())).status,401);});
test("OAuth rejects wrong state and non-allow-listed login",async()=>{const e=await env();let request=new Request("https://api.test/auth/callback?state=wrong");assert.equal((await authCallback(request,e)).status,403);const pending=await signed(JSON.stringify({state:"ok",verifier:"v",exp:Date.now()+60000}),secret);const old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>Response.json(++calls===1?{access_token:"token"}:{login:"someone-else"});request=new Request("https://api.test/auth/callback?state=ok&code=x",{headers:{cookie:`review_oauth=${encodeURIComponent(pending)}`}});assert.equal((await authCallback(request,e)).status,403);globalThis.fetch=old;});
test("draft save requires CSRF, versions optimistically, and rejects oversize",async()=>{const e=await env();const revision="a".repeat(64);const headers=await authHeaders();let request=new Request(`https://api.test/drafts/${revision}/1`,{method:"PUT",headers:{...headers,"x-review-csrf":"wrong"},body:JSON.stringify({version:0,decisions:{}})});assert.equal((await worker.fetch(request,e)).status,403);request=new Request(`https://api.test/drafts/${revision}/1`,{method:"PUT",headers,body:JSON.stringify({version:0,decisions:{x:{action:"accept"}}})});assert.equal((await worker.fetch(request,e)).status,200);request=new Request(`https://api.test/drafts/${revision}/1`,{method:"PUT",headers,body:JSON.stringify({version:0,decisions:{}})});assert.equal((await worker.fetch(request,e)).status,409);request=new Request(`https://api.test/drafts/${revision}/2`,{method:"PUT",headers,body:JSON.stringify({version:0,decisions:{x:"z".repeat(520000)}})});assert.equal((await worker.fetch(request,e)).status,413);});
test("submit is immutable/idempotent and maps GitHub failures",async()=>{const doc=await payload();for(const code of [401,403,409,429,500]){const e=await env({SUBMISSION_BROKER:{create:async()=>{throw Object.assign(new Error("upstream"),{status:code});}}});const response=await submit(e,doc);assert.equal(response.status,code===500?502:code);}const e=await env({SUBMISSION_BROKER:{create:async()=>({pr_url:"https://github.test/pr/1"})}});assert.equal((await submit(e,doc)).status,201);const second=await submit(e,doc);assert.equal(second.status,200);assert.equal((await second.json()).idempotent,true);});
test("malformed and incomplete final payloads are rejected",async()=>{const e=await env({SUBMISSION_BROKER:{create:async()=>assert.fail("must not write")}});const doc=await payload();doc.sargas.pop();assert.equal((await submit(e,doc)).status,422);});
test("concurrent same-version draft saves cannot both win (lost-update regression)",async()=>{const e=await env();const revision="b".repeat(64);const headers=await authHeaders();const put=decisions=>new Request(`https://api.test/drafts/${revision}/1`,{method:"PUT",headers,body:JSON.stringify({version:0,decisions})});const [a,b]=await Promise.all([worker.fetch(put({who:"A"}),e),worker.fetch(put({who:"B"}),e)]);assert.equal([a.status,b.status].sort().join(","),"200,409");const final=await worker.fetch(new Request(`https://api.test/drafts/${revision}/1`,{headers}),e);const body=await final.json();assert.equal(body.version,1);assert.ok(body.decisions.who==="A"||body.decisions.who==="B","the surviving draft is one full save, not a mix");});
test("re-save after a 409 uses the returned version (UPDATE compare-and-set path)",async()=>{const e=await env();const revision="c".repeat(64);const headers=await authHeaders();const put=v=>new Request(`https://api.test/drafts/${revision}/1`,{method:"PUT",headers,body:JSON.stringify({version:v,decisions:{step:v}})});assert.equal((await worker.fetch(put(0),e)).status,200);const ok=await worker.fetch(put(1),e);assert.equal(ok.status,200);assert.equal((await ok.json()).version,2);assert.equal((await worker.fetch(put(1),e)).status,409);assert.equal((await worker.fetch(put(2),e)).status,200);});
