const enc=new TextEncoder();
export const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const unb64=value=>Uint8Array.from(atob(value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=")),c=>c.charCodeAt(0));
async function hmac(secret,value){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"]);return b64(await crypto.subtle.sign("HMAC",key,enc.encode(value)));}
export async function signed(value,secret){return `${b64(enc.encode(value))}.${await hmac(secret,b64(enc.encode(value)))}`;}
export async function verified(token,secret){if(!token)return null;const [body,sig]=token.split(".");if(!body||!sig||await hmac(secret,body)!==sig)return null;try{return JSON.parse(new TextDecoder().decode(unb64(body)));}catch(_){return null;}}
export function cookies(request){return Object.fromEntries((request.headers.get("cookie")||"").split(/;\s*/).filter(Boolean).map(v=>{const i=v.indexOf("=");return [v.slice(0,i),decodeURIComponent(v.slice(i+1))];}));}
export const cookie=(name,value,maxAge=900,httpOnly=true)=>`${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; Secure; SameSite=Lax${httpOnly?"; HttpOnly":""}`;
export async function session(request,env){const data=await verified(cookies(request).review_session,env.SESSION_SECRET);if(!data||data.exp<Date.now()||data.reviewer!=="Костина")return null;return data;}
export function requireCsrf(request){const c=cookies(request).review_csrf;return Boolean(c&&request.headers.get("x-review-csrf")===c);}
export async function authStart(request,env){const state=b64(crypto.getRandomValues(new Uint8Array(24)));const verifier=b64(crypto.getRandomValues(new Uint8Array(32)));const challenge=b64(await crypto.subtle.digest("SHA-256",enc.encode(verifier)));const pending=await signed(JSON.stringify({state,verifier,exp:Date.now()+600000}),env.SESSION_SECRET);const url=new URL("https://github.com/login/oauth/authorize");url.searchParams.set("client_id",env.GITHUB_OAUTH_CLIENT_ID);url.searchParams.set("redirect_uri",`${new URL(request.url).origin}/auth/callback`);url.searchParams.set("scope","read:user");url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");return new Response(null,{status:302,headers:{location:url.toString(),"set-cookie":cookie("review_oauth",pending,600)}});}
export async function authCallback(request,env){const url=new URL(request.url);const pending=await verified(cookies(request).review_oauth,env.SESSION_SECRET);if(!pending||pending.exp<Date.now()||pending.state!==url.searchParams.get("state"))return Response.json({error:"invalid OAuth state"},{status:403});const tokenResponse=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:JSON.stringify({client_id:env.GITHUB_OAUTH_CLIENT_ID,client_secret:env.GITHUB_OAUTH_CLIENT_SECRET,code:url.searchParams.get("code"),code_verifier:pending.verifier})});const token=await tokenResponse.json();if(!token.access_token)return Response.json({error:"OAuth exchange failed"},{status:401});const userResponse=await fetch("https://api.github.com/user",{headers:{authorization:`Bearer ${token.access_token}`,"user-agent":"CommentaryStrategies-review"}});const user=await userResponse.json();if(!user.login||user.login.toLowerCase()!==String(env.ALLOWED_GITHUB_LOGIN||"").toLowerCase())return Response.json({error:"GitHub login is not allow-listed"},{status:403});const csrf=b64(crypto.getRandomValues(new Uint8Array(24)));const value=await signed(JSON.stringify({reviewer:"Костина",login:user.login,csrf,exp:Date.now()+3600000}),env.SESSION_SECRET);const headers=new Headers({location:env.PAGES_PORTAL_URL||"https://gasyoun.github.io/CommentaryStrategies/data/apparatus/"});headers.append("set-cookie",cookie("review_session",value,3600));headers.append("set-cookie",cookie("review_csrf",csrf,3600,false));headers.append("set-cookie",cookie("review_oauth","",0));return new Response(null,{status:302,headers});}
